
api_version = "unstable"


[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "my-subscription-ext"
type = "ui_extension"


# Both targets need to be specified for the extensions to work
[[extensions.targeting]]
module = "./src/ProductExtension.jsx"
target = "admin.product-purchase-option.action.render"

[[extensions.targeting]]
module = "./src/ProductVariantExtension.jsx"
target = "admin.product-variant-purchase-option.action.render"

# Valid extension targets:

# Product index and detail pages
# - admin.product-purchase-option.action.render

# Product variant detail pages
# - admin.product-variant-purchase-option.action.render
